create table NM_Notification (
	uuid_ VARCHAR(75) null,
	notificationId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	status INTEGER,
	statusByUserId LONG,
	statusByUserName VARCHAR(75) null,
	statusDate DATE null,
	type_ VARCHAR(75) null,
	always BOOLEAN,
	mail BOOLEAN,
	sms BOOLEAN,
	web BOOLEAN,
	notificationAttributes VARCHAR(75) null
);